library(tidyverse)
library(gapminder)

select(gapminder)
select(gapminder, year, lifeExp, country)
select(gapminder, country, continent, year, lifeExp)
select(gapminder, country:lifeExp)
select(gapminder, -lifeExp)
select(gapminder, everything())
select(gapminder, continent, everything())
select(gapminder, Continent = continent, Year = year)
arrange(gapminder, year)
arrange(gapminder,-year)
arrange(gapminder,+year)
arrange(gapminder, year, lifeExp)
# Back to the Guide